### ISSUE TITLE
Firebase cloud storage

### ISSUE THREAD

**Issue by bil-ash** [ReallySmallSoftware/cordova-plugin-firestore#1]
All the firebase plugins created by you are really superb.
It would be really helpfull if you could create a plugin for firebase cloud storage also. Then we would have all the methods of firebase file i/o via cordova plugins. There dosen't seem to be cordova plugin for cloud storage at the moment. Even an android-only implementation would be great.

**Comment by ReallySmallSoftware** [comment]
Thank you. I haven't been doing this all that long so it's nice to hear your feedback.

My plugins are generally driven by my own needs, but I will make  a note of your suggestion. The storage API seems like it should be OK to wrap so it would make a good next target for me to attempt.
