### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by andiamann** [ReallySmallSoftware/cordova-plugin-firestore#3]
Build not working for me, any idea how to resolve?

>FAILURE: Build failed with an exception.

>What went wrong:
>Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
>java.lang.RuntimeException: java.lang.RuntimeException: >com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

I am using, 
Ionic with cordova 8
plugins
cordova-plugin-firebase-authentication
cordova-plugin-googleplus
cordova-plugin-admobpro

**Comment by gabrielpotumati** [comment]
same error, i fixed?

**Comment by andiamann** [comment]
> same error, i fixed?

sometimes after install one plugin you need to remove and add the platform again, in my case I don't record what I did, maybe I upgrade the gradle or added a multiDexEnabled true on build.gradle file
or the solution was remove and add the platform, I hope I help a little.

**Comment by gabrielpotumati** [comment]
tks, helped me to find way
